- id: '1728813664008'
  alias: Bedroom - Curtains - Button
  use_blueprint:
    path: local/smart-scene-switch.yaml
    input:
      mode: restart
      switch: sensor.sss02_action
      button_short_press:
      - action: cover.toggle
        target:
          entity_id: cover.curtains_bedroom
      button_double_press:
      - action: cover.set_cover_position
        data:
          position: 30
        target:
          entity_id: cover.curtains_bedroom
      button_long_press:
      - action: cover.set_cover_position
        data:
          position: 10

- id: '8196071004937'
  alias: Bedroom - Curtains - Fajr
  use_blueprint:
    path: local/peek-curtains.yaml
    input:
      occupancy_entity: binary_sensor.presence_bedroom
      cover_target: cover.curtains_bedroom
      trigger:
        - platform: sun
          event: sunrise
          offset: "-00:15:00"

- id: '6573097207207'
  alias: Bedroom - Curtains - Maghrib
  use_blueprint:
    path: local/peek-curtains.yaml
    input:
      occupancy_entity: binary_sensor.presence_bedroom
      cover_target: cover.curtains_bedroom
      trigger:
        - platform: sun
          event: sunset

- id: '5219250874162'
  alias: Bedroom - Curtains - Wake Up
  trigger:
    - platform: time
      at: "09:00:00"
  action:
    - service: cover.set_cover_position
      target:
        entity_id: cover.curtains_bedroom
      data:
        position: 30
