- id: '1112311712098'
  alias: Bedroom - Lights - Maghrib
  use_blueprint:
    path: local/maghrib-lights.yaml
    input:
      occupancy_entity: binary_sensor.presence_bedroom
      light_target:
        - light.esp01_bed_light
        - switch.zss02_l1

- id: '8513465843864'
  alias: Bedroom - Lights - Occupancy
  use_blueprint:
    path: local/occupancy-lights.yaml
    input:
      occupancy_entity: binary_sensor.presence_bedroom
      light_target:
        - light.esp01_bed_light
        - switch.zss02_l1

- id: "8513465843844"
  alias: Bedroom - Lights - Fajr
  condition:
    - condition: state
      entity_id: binary_sensor.presence_bedroom
      state: "on"
  triggers:
    - platform: sun
      event: sunrise
      offset: "-00:30:00"
  action:
    - action: light.turn_on
      target:
        entity_id: light.esp01_bed_light
      data:
        transition: 1
        brightness_pct: 50
    - action: light.turn_off
      target:
        entity_id: light.esp01_bed_light
      data:
        transition: 1200

- id: "1736361188282"
  alias: Bedroom - Lights - Night
  mode: single
  triggers:
    - trigger: numeric_state
      entity_id:
        - sensor.esp01_ultrasonic_right_sensor
        - sensor.esp01_ultrasonic_left_sensor
      below: 2
  conditions: []
  actions:
    - action: light.turn_on
      data:
        transition: 2
        brightness_pct: 20
      target:
        entity_id: light.esp01_bed_light
    - wait_for_trigger:
        - trigger: state
          entity_id:
            - binary_sensor.esp01_bed_right_occupancy
            - binary_sensor.esp01_bed_left_occupancy
          from: "off"
          to: "on"
      timeout:
        minutes: 5
    - action: light.turn_off
      target:
        entity_id: light.esp01_bed_light
