blueprint:
  name: Maghrib Lights
  description: Turn on lights at Maghrib.
  domain: automation
  input:
    occupancy_entity:
      name: Occupancy
      description: Occupancy is detected.
      selector:
        entity:
          domain: binary_sensor
          device_class:
            - occupancy
            - presence
    light_target:
      description:  light on
      name: Light
      selector:
        entity:
          domain:
            - light
          multiple: true

mode: single
max_exceeded: silent

trigger:
  - platform: sun
    event: sunset

variables:
  lights: !input "light_target"

condition:
  - condition: state
    entity_id: !input occupancy_entity
    state: "on"

action:
  - action: light.turn_on
    target:
      entity_id: '{{ expand(lights) }}'
    data:
      transition: 600
      brightness_pct: 100
