blueprint:
  name: Occupancy Lights
  description: Turn on a light when room is occupied.
  domain: automation
  input:
    occupancy_entity:
      name: Occupancy
      description: Occupancy is detected.
      selector:
        entity:
          domain: binary_sensor
          device_class: occupancy
    light_target:
      description:  light on
      name: Light
      selector:
        entity:
          domain:
            - light
          multiple: true
    no_occupancy_wait:
      name: Wait time
      description: Time to leave the light on after last motion is detected.
      default: 300
      selector:
        number:
          min: 0
          max: 3600
          unit_of_measurement: seconds

mode: restart
max_exceeded: silent

trigger:
  - platform: state
    entity_id: !input occupancy_entity
    from: "off"
    to: "on"

condition:
  - condition: sun
    after: sunset

variables:
  lights: !input "light_target"

action:
  - action: light.turn_on
    target:
      entity_id:
        !input "light_target"
  - wait_for_trigger:
      platform: state
      entity_id: !input occupancy_entity
      from: "on"
      to: "off"
  - delay: !input no_occupancy_wait
  - action: light.turn_off
    target:
      entity_id:
        !input "light_target"
