permit_join: true
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://mqtt
homeassistant: true
serial:
  port: /dev/ttyUSB0
frontend:
  port: 8080
advanced:
  network_key:
    - 70
    - 109
    - 245
    - 245
    - 114
    - 120
    - 223
    - 93
    - 68
    - 202
    - 232
    - 115
    - 125
    - 61
    - 245
    - 112
devices:
  '0xa4c138154539d294':
    friendly_name: THS04
  '0xa4c138dfb84b0835':
    friendly_name: THS02
  '0xa4c138f18721c38a':
    friendly_name: SSK01
  '0x0ceff6fffebf35e4':
    friendly_name: '0x0ceff6fffebf35e4'
  '0x70b3d52b600a7da5':
    friendly_name: ZSS01
  '0xa4c13868473ca9ee':
    friendly_name: MS03
  '0xa4c13868cfe333f7':
    friendly_name: DS02
  '0xa4c138015e42e643':
    friendly_name: WB-4G-02
  '0xa4c1380fbcbfaae9':
    friendly_name: MS04
  '0xa4c1388700fdf966':
    friendly_name: SSS02
  '0xa4c138444f544b06':
    friendly_name: ZSS02
  '0xa4c138ffcb285131':
    friendly_name: PS03
  '0xa4c138cb0365aa9d':
    friendly_name: WB-4G-01
  '0xa4c1384b195eaec6':
    friendly_name: MS02
  '0xa4c138c33628f3cb':
    friendly_name: MS06
  '0xa4c1389623108d0b':
    friendly_name: PS01
  '0xa4c1380ed7dfd452':
    friendly_name: SSS01
  '0x842712fffe476f27':
    friendly_name: Curtains - Bedroom
  '0xa4c138f77a85bfc9':
    friendly_name: '0xa4c138f77a85bfc9'
  '0xa4c1387941d710ee':
    friendly_name: '0xa4c1387941d710ee'
  '0xa4c13870c3f8c16f':
    friendly_name: '0xa4c13870c3f8c16f'
  '0xa4c1381bb53c1b1f':
    friendly_name: MS01
  '0xa4c138f0f239bc9f':
    friendly_name: ZSS3G01
  '0xa4c1383bd1256b7d':
    friendly_name: ZSS3G02
  '0xa4c138d6c7435263':
    friendly_name: MS08
  '0x8c65a3fffec7cb72':
    friendly_name: Curtains - Living Room - Side
  '0x8c65a3fffec7aa3f':
    friendly_name: ' WSS01'
  '0xa4c138b425c8d288':
    friendly_name: ZMS02-2G
  '0xa4c13815f5f4d4da':
    friendly_name: THS01
  '0x70b3d52b600a7ce1':
    friendly_name: Z-PLG-01
  '0xa4c138e1353a8e8e':
    friendly_name: PS02
  '0xa4c1383c8ea2bb96':
    friendly_name: THS05
  '0xa4c138310c4f5967':
    friendly_name: ZMS01-1G
  '0xa4c1380f716b1387':
    friendly_name: DS01
external_converters:
  - curtain-bot.js
