# Living Room sensors
- sensor:
  - name: "Average Temperature - Living Room"
    unit_of_measurement: "°C"
    state: >
      {% set area = 'Living Room' %}
      {% set temps = states.sensor
        | selectattr('attributes.device_class', 'equalto', 'temperature')
        | selectattr('entity_id', 'ne', this.entity_id)
        | rejectattr('state', 'in', ['unavailable', 'unknown', '0'])
        | selectattr('state', 'is_number')
        | selectattr('entity_id', 'in', area_entities(area))
        | selectattr('entity_id', 'in', label_entities('Sensor'))
        | map(attribute='state') | map('float') | list %}
      {% if temps | length > 0 %}
        {{ (temps | sum) / (temps | length) }}
      {% else %}
        unknown
      {% endif %}

  - name: "Average Humidity - Living Room"
    unit_of_measurement: "%"
    state: >
      {% set area = 'Living Room' %}
      {% set humidities = states.sensor
        | selectattr('attributes.device_class', 'equalto', 'humidity')
        | selectattr('entity_id', 'ne', this.entity_id)
        | rejectattr('state', 'in', ['unavailable', 'unknown', '0'])
        | selectattr('state', 'is_number')
        | selectattr('entity_id', 'in', area_entities(area))
        | selectattr('entity_id', 'in', label_entities('Sensor'))
        | map(attribute='state') | map('float') | list %}
      {% if humidities | length > 0 %}
        {{ (humidities | sum) / (humidities | length) }}
      {% else %}
        unknown
      {% endif %}
