- id: '4448387364818'
  alias: Laundry - Lights
  description: ""
  mode: single
  triggers:
    - entity_id:
        - binary_sensor.moving_presence_laundry
      from: "off"
      to: "on"
      id: motion-on
      trigger: state
    - entity_id:
        - binary_sensor.moving_presence_laundry
      from: "on"
      to: "off"
      for:
        seconds: 10
      id: motion-off
      trigger: state
    - id: door-closed
      platform: state
      entity_id: binary_sensor.z_dr_01_contact
      from: 'on'
      to: 'off'
    - id: door-open
      platform: state
      entity_id: binary_sensor.z_dr_01_contact
      from: 'off'
      to: 'on'
  conditions: []
  actions:
    - choose:
        - conditions:
            - condition: trigger
              id:
                - motion-on
                - door-open
            - condition: state
              entity_id: binary_sensor.z_dr_01_contact
              state: 'on'
          sequence:
            - action: light.turn_on
              target:
                area_id: laundry
        - conditions:
            - condition: trigger
              id:
                - motion-off
                - door-closed
          sequence:
            - action: light.turn_off
              target:
                area_id: laundry
