- id: '1736176173682'
  alias: Bedroom - Bed Controls - Aziz
  description: ''
  use_blueprint:
    path: local/ts004-wss.yaml
    input:
      switch:
      - sensor.wss04_action
      button_one_short_press:
      - action: cover.toggle
        metadata: {}
        data: {}
        target:
          area_id: bedroom
      button_one_double_press:
      - action: cover.set_cover_position
        metadata: {}
        data:
          position: 30
        target:
          area_id: bedroom
      button_two_short_press:
      - if:
        - condition: or
          conditions:
          - condition: time
            before: '23:00:00'
        then:
        - action: light.toggle
          metadata: {}
          data:
            transition: 1
            brightness_pct: 100
          target:
            entity_id: light.esp01_bed_light
        else:
        - action: light.toggle
          metadata: {}
          data:
            transition: 1
            brightness_pct: 30
          target:
            entity_id: light.esp01_bed_light
      button_two_double_press:
      - action: light.toggle
        metadata: {}
        data: {}
        target:
          entity_id: light.zss02_l1
      button_three_short_press:
      - if:
        - condition: state
          entity_id: switch.wss01_socket_1
          state: 'on'
        then:
        - action: switch.turn_off
          entity_id: switch.wss01_socket_1
        else:
        - action: switch.turn_on
          data: {}
          target:
            entity_id: switch.wss01_socket_1
      button_three_double_press:
      - if:
        - condition: state
          entity_id: switch.wss01_socket_1
          state: 'on'
        then:
        - action: switch.turn_off
          entity_id: switch.wss01_socket_1
        else:
        - action: script.turn_on
          data:
            variables:
              heater: switch.wss01_socket_1
          target:
            entity_id: script.control_bed_heater
- id: '1736176998592'
  alias: Bedroom - Bed Controls - Nisrin
  description: ''
  use_blueprint:
    path: local/ts004-wss.yaml
    input:
      switch:
      - sensor.wss05_action
      button_one_short_press:
      - action: cover.toggle
        metadata: {}
        data: {}
        target:
          area_id: bedroom
      button_one_double_press:
      - action: cover.set_cover_position
        metadata: {}
        data:
          position: 30
        target:
          area_id: bedroom
      button_two_short_press:
      - if:
        - condition: or
          conditions:
          - condition: time
            after: '23:00:00'
        then:
        - action: light.toggle
          metadata: {}
          data:
            transition: 1
            brightness_pct: 30
          target:
            entity_id: light.esp01_bed_light
        else:
        - action: light.toggle
          metadata: {}
          data:
            transition: 1
            brightness_pct: 100
          target:
            entity_id: light.esp01_bed_light
      button_two_double_press:
      - action: light.toggle
        metadata: {}
        data: {}
        target:
          entity_id: light.zss02_l1
      button_four_short_press:
      - if:
        - condition: state
          entity_id: switch.wss02_socket_1
          state: 'on'
        then:
        - action: switch.turn_off
          entity_id: switch.wss02_socket_1
        else:
        - action: switch.turn_on
          data: {}
          target:
            entity_id: switch.wss02_socket_1
      button_four_double_press:
      - if:
        - condition: state
          entity_id: switch.wss02_socket_1
          state: 'on'
        then:
        - action: switch.turn_off
          entity_id: switch.wss02_socket_1
        else:
        - action: script.turn_on
          data:
            variables:
              heater: switch.wss02_socket_1
          target:
            entity_id: script.control_bed_heater
- id: '1736361188282'
  alias: Bedroom - Lights - Night
  description: ''
  triggers:
  - trigger: numeric_state
    entity_id:
    - sensor.esp01_ultrasonic_right_sensor
    - sensor.esp01_ultrasonic_left_sensor
    below: 2
  conditions: []
  actions:
  - action: light.turn_on
    metadata: {}
    data:
      transition: 2
      brightness_pct: 20
    target:
      entity_id: light.esp01_bed_light
  - wait_for_trigger:
    - trigger: state
      entity_id:
      - binary_sensor.esp01_bed_right_occupancy
      - binary_sensor.esp01_bed_left_occupancy
      from: 'off'
      to: 'on'
    timeout:
      hours: 0
      minutes: 5
      seconds: 0
      milliseconds: 0
  - type: turn_off
    device_id: 2bc50fb9fb244a80baf0ec344bd83ef0
    entity_id: ec0f3ac6e30c6a4234b532c0a52d1df1
    domain: light
  mode: single
- id: '1736361583980'
  alias: Reset Night Mode
  description: ''
  triggers:
  - trigger: sun
    event: sunrise
    offset: 0
  conditions: []
  actions:
  - action: input_boolean.turn_off
    metadata: {}
    data: {}
    target:
      label_id: flag_night_mode
  mode: single
- id: '1736361791549'
  alias: Set - Bedroom - Night Mode
  description: ''
  triggers:
  - trigger: time
    at: '23:00:00'
  - trigger: state
    entity_id:
    - binary_sensor.esp01_bed_right_occupancy
    - binary_sensor.esp01_bed_left_occupancy
    from: 'off'
    to: 'on'
    for:
      hours: 0
      minutes: 20
      seconds: 0
  conditions:
  - condition: time
    after: '21:00:00'
  - condition: state
    entity_id: binary_sensor.occupancy_bedroom
    state: 'on'
  actions:
  - action: input_boolean.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: input_boolean.bedroom_night_mode
  mode: single
- id: '1736423920854'
  alias: Mom's Room - Lights - Passage
  description: ''
  use_blueprint:
    path: local/occupancy-lights.yaml
    input:
      occupancy_entity: binary_sensor.ms08_occupancy
      light_target:
      - light.zss3g02_right
      no_occupancy_wait: 30
- id: '1736503798847'
  alias: Aquarium - Lights
  description: ''
  triggers:
  - trigger: time
    at: '13:00:00'
    id: time-on
  - trigger: time
    at: '19:00:00'
    id: time-off
  conditions: []
  actions:
  - if:
    - condition: trigger
      id:
      - time-on
    then:
    - action: light.turn_on
      metadata: {}
      data: {}
      target:
        device_id: cdd8a4f42cf5052d2c020771d66c1959
    else:
    - action: light.turn_off
      metadata: {}
      data: {}
      target:
        device_id: cdd8a4f42cf5052d2c020771d66c1959
  mode: single
- id: '1736688453558'
  alias: Tag Aquarium Light Heater is scanned
  description: ''
  triggers:
  - trigger: tag
    tag_id: e886a1ae-4a3f-4138-b862-7395f2c8eccb
  conditions: []
  actions:
  - action: switch.toggle
    metadata: {}
    data: {}
    target:
      entity_id:
      - switch.sp23_aquarium_heater_socket_1
      - switch.sp22_aquarium_filter_socket_1
  mode: single
- id: '1739712917701'
  alias: Tag Aquarium Light is scanned
  description: ''
  triggers:
  - trigger: tag
    tag_id: 270bd906-01e8-4d84-bf0f-bf42103e532a
  conditions: []
  actions:
  - action: light.toggle
    metadata: {}
    data: {}
    target:
      device_id: cdd8a4f42cf5052d2c020771d66c1959
  mode: single
