control_bed_heater:
  alias: Control bed heater
  fields:
    heater:
      selector:
        entity: {}
      name: Heater
      required: true
    duration:
      selector:
        duration:
      default:
        hours: 1
        minutes: 0
        seconds: 0
        milliseconds: 0
  sequence:
  - action: switch.turn_on
    target:
      entity_id: '{{ heater }}'
  - delay: "{{ duration }}"
  - action: switch.turn_off
    target:
      entity_id: '{{ heater }}'

bukhur_quick:
  alias: Bukhur Quick
  sequence:
  - action: switch.turn_on
    metadata: {}
    data: {}
    target:
      label_id: bukhur
  - delay:
      hours: 0
      minutes: 10
      seconds: 0
      milliseconds: 0
  - action: switch.turn_off
    metadata: {}
    data: {}
    target:
      label_id: bukhur
  description: ''
