blueprint:
  name: Occupancy Lights
  description: Turn on a light when room is occupied.
  domain: automation
  input:
    occupancy_entity:
      name: Occupancy
      description: Occupancy is detected.
      selector:
        entity:
          domain: binary_sensor
          device_class: occupancy
    light_target:
      description:  light on
      name: Light
      selector:
        target:
          entity:
            domain: light
    no_occupancy_wait:
      name: Wait time
      description: Time to leave the light on after last motion is detected.
      default: 300
      selector:
        number:
          min: 0
          max: 3600
          unit_of_measurement: seconds
    flag:
      name: Enabled Flag
      description: Toggle that decides whether to run this automation or not.
      selector:
        entity:
          domain: input_boolean

# If motion is detected within the delay,
# we restart the script.
mode: restart
max_exceeded: silent

# automation normaly
trigger:
  - platform: state
    entity_id: !input occupancy_entity
    from: "off"
    to: "on"
  - platform: sun
    event: sunset

condition:
  - conditions:
    - condition: sun
      after: sunset

action:
  - action: light.turn_on
    target: !input light_target
  - wait_for_trigger:
      platform: state
      entity_id: !input occupancy_entity
      from: "on"
      to: "off"
  - delay: !input no_occupancy_wait
  - action: light.turn_off
    target: !input light_target
